module.exports = {
  A: '20 Round kicks',
  B: '13 Jump Squats',
  C: '5 Spin Hook Kicks',
  D: '30 Axe Kicks',
  E: '20 Pushups',
  F: '10 Burpees',
  G: '15 Side Kicks',
  H: '5 Jump Split Kicks',
  I: '20 Punches',
  J: '15 Palm Strikes',
  K: '15 Jump Front Kicks',
  L: '20 Skipping Round Kicks',
  M: '15 Skipping Side Kicks',
  N: '50 Jumping Jacks',
  O: '10 Jump Side Kicks',
  P: '15 Jump Pop Round Kicks',
  Q: '5 Double Round Kicks, Low, High',
  R: '15 Burpees ',
  S: '20 Front Kicks',
  T: '15 Skipping Axe Kicks',
  U: '5 Spin Side Kicks',
  V: '20 Leg Ups',
  W: '5 Close-hand ("Diamond") Pushups',
  X: '15 Crunches',
  Y: '20 Skipping Hook Kicks',
  Z: '15 Lead Leg Front Kicks'
}
